/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.110
 * Generated at: 2025-12-04 00:53:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.persistence.*;
import org.openxava.jpa.XPersistence;
import org.example.ProyectoPOO.model.bodega.Paquete;
import org.example.ProyectoPOO.model.bodega.Movimiento;
import java.util.List;
import java.time.format.DateTimeFormatter;

public final class rastreo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.persistence");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(7);
    _jspx_imports_classes.add("org.openxava.jpa.XPersistence");
    _jspx_imports_classes.add("org.example.ProyectoPOO.model.bodega.Movimiento");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("org.example.ProyectoPOO.model.bodega.Paquete");
    _jspx_imports_classes.add("java.time.format.DateTimeFormatter");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Rastreo de Envíos - ProyectoPOO</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: \"Segoe UI\", Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("            background-color: #f4f7f6;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .header {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            background: linear-gradient(135deg, #2980b9, #2c3e50);\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 20px 40px;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            box-shadow: 0 2px 8px rgba(0,0,0,0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .header h1 {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            font-size: 26px;\r\n");
      out.write("            letter-spacing: 1px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .container {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            max-width: 900px;\r\n");
      out.write("            padding: 30px 15px 40px;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .search-box {\r\n");
      out.write("            background: white;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            box-shadow: 0 2px 8px rgba(0,0,0,0.08);\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-wrap: wrap;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .search-box label {\r\n");
      out.write("            flex-basis: 100%;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            color: #2c3e50;\r\n");
      out.write("            margin-bottom: 5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .search-box input[type=\"text\"] {\r\n");
      out.write("            flex: 1;\r\n");
      out.write("            min-width: 180px;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("            border: 1px solid #ccc;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .search-box button {\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            background-color: #e67e22;\r\n");
      out.write("            color: white;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: background 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .search-box button:hover {\r\n");
      out.write("            background-color: #d35400;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .result-card {\r\n");
      out.write("            background: white;\r\n");
      out.write("            margin-top: 25px;\r\n");
      out.write("            padding: 22px;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            border-left: 4px solid #27ae60;\r\n");
      out.write("            box-shadow: 0 2px 10px rgba(0,0,0,0.05);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .result-header {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("            flex-wrap: wrap;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .result-header h3 {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .status-badge {\r\n");
      out.write("            background-color: #27ae60;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 4px 10px;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            font-size: 0.9em;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .result-card p {\r\n");
      out.write("            margin: 5px 0;\r\n");
      out.write("            color: #34495e;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .timeline {\r\n");
      out.write("            margin-top: 18px;\r\n");
      out.write("            border-left: 2px solid #ddd;\r\n");
      out.write("            padding-left: 18px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .timeline-item {\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .timeline-item::before {\r\n");
      out.write("            content: \"\";\r\n");
      out.write("            width: 10px;\r\n");
      out.write("            height: 10px;\r\n");
      out.write("            background-color: #3498db;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            left: -6px;\r\n");
      out.write("            top: 4px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .timeline-item strong {\r\n");
      out.write("            color: #2c3e50;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .timeline-item small {\r\n");
      out.write("            color: #7f8c8d;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .info-text {\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("            color: #7f8c8d;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .error-msg {\r\n");
      out.write("            color: #c0392b;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            margin-top: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes fadeIn {\r\n");
      out.write("            from { opacity: 0; transform: translateY(10px); }\r\n");
      out.write("            to   { opacity: 1; transform: translateY(0); }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .result-card, .search-box {\r\n");
      out.write("            animation: fadeIn 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("    <h1>Courier Express – Rastreo de Envíos</h1>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"search-box\">\r\n");
      out.write("        <form method=\"get\" action=\"rastreo.jsp\" style=\"display:flex; flex-wrap:wrap; gap:10px; width:100%;\">\r\n");
      out.write("            <label for=\"tracking\">Ingresa tu código de rastreo</label>\r\n");
      out.write("            <input type=\"text\"\r\n");
      out.write("                   id=\"tracking\"\r\n");
      out.write("                   name=\"tracking\"\r\n");
      out.write("                   placeholder=\"Ej: USA123456\"\r\n");
      out.write("                   required\r\n");
      out.write("                   value=\"");
      out.print( request.getParameter("tracking") != null ? request.getParameter("tracking") : "" );
      out.write("\">\r\n");
      out.write("            <button type=\"submit\">Rastrear</button>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    ");

        String trackingCode = request.getParameter("tracking");

        if (trackingCode != null && !trackingCode.trim().isEmpty()) {
            EntityManager em = XPersistence.getManager();

            try {
                String jpql = "SELECT p FROM Paquete p WHERE p.trackingProveedor = :code";
                TypedQuery<Paquete> query = em.createQuery(jpql, Paquete.class);
                query.setParameter("code", trackingCode.trim());

                Paquete paquete = query.getSingleResult();

                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"result-card\">\r\n");
      out.write("        <div class=\"result-header\">\r\n");
      out.write("            <h3>📦 Paquete #");
      out.print( paquete.getId() );
      out.write("</h3>\r\n");
      out.write("            <span class=\"status-badge\">");
      out.print( paquete.getEstadoActual() );
      out.write("</span>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <p><strong>Descripción:</strong> ");
      out.print( paquete.getDescripcion() );
      out.write("</p>\r\n");
      out.write("        <p><strong>Código de tracking:</strong> ");
      out.print( paquete.getTrackingProveedor() );
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("        <hr>\r\n");
      out.write("\r\n");
      out.write("        <h4>Ubicación actual</h4>\r\n");
      out.write("        <p>\r\n");
      out.write("            ");
      out.print( (paquete.getUbicacionActual() != null)
                    ? paquete.getUbicacionActual().getNombre()
                    : "En tránsito internacional / Sin sucursal asignada" );
      out.write("\r\n");
      out.write("        </p>\r\n");
      out.write("\r\n");
      out.write("        ");

            List<Movimiento> historial = paquete.getHistorial();
            if (historial != null && !historial.isEmpty()) {
        
      out.write("\r\n");
      out.write("        <h4>Historial de movimientos</h4>\r\n");
      out.write("        <div class=\"timeline\">\r\n");
      out.write("            ");

                for (Movimiento mov : historial) {
            
      out.write("\r\n");
      out.write("            <div class=\"timeline-item\">\r\n");
      out.write("                <strong>");
      out.print( mov.getEstado() );
      out.write("</strong><br>\r\n");
      out.write("                <small>\r\n");
      out.write("                    ");
      out.print( (mov.getTimestamp() != null)
                            ? mov.getTimestamp().format(formatter)
                            : "" );
      out.write("\r\n");
      out.write("                </small>\r\n");
      out.write("                <br>\r\n");
      out.write("                ");
      out.print( mov.getDescripcion() != null ? mov.getDescripcion() : "" );
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            ");

                }
            
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        ");

        } else {
        
      out.write("\r\n");
      out.write("        <p class=\"info-text\">No hay movimientos registrados aún.</p>\r\n");
      out.write("        ");

            }
        
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    ");

    } catch (NoResultException e) {
    
      out.write("\r\n");
      out.write("    <div class=\"search-box info-text\" style=\"margin-top: 20px;\">\r\n");
      out.write("        <h3 class=\"error-msg\">No encontrado</h3>\r\n");
      out.write("        <p>No pudimos encontrar un paquete con el código <strong>");
      out.print( trackingCode );
      out.write("</strong>.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");

    } catch (Exception e) {
    
      out.write("\r\n");
      out.write("    <p class=\"error-msg\">\r\n");
      out.write("        Error del sistema: ");
      out.print( e.getMessage() );
      out.write("\r\n");
      out.write("    </p>\r\n");
      out.write("    ");

                e.printStackTrace();
            }
        }
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
